name: 'name tag minha primeira action usando typescript'
description: 'description tag aqui vem uma descricao'
author: 'Gabriel do Nascimento de Carvalho'
inputs:
  milliseconds: 1000
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
